# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: xygeni-scanner@1
  inputs:
    xygeniToken: 'xyo_11dc679e62463e1193827a20214200abd23679afb1ac1910117689c69fa2d915'
    scanDirectory: '$(Build.Repository.LocalPath)'
    suspectdeps: true
    iac: true
